[database]
DB_HOST = "aws-1-ap-southeast-1.pooler.supabase.com"
DB_NAME = "postgres"
DB_USER = "postgres.tmssypansbsalzcqwqys"
DB_PASS = "midsemester"
DB_PORT = "5432"

[supabase]
SUPABASE_URL = "https://tmssypansbsalzcqwqys.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc3N5cGFuc2JzYWx6Y3F3cXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTMxMzMsImV4cCI6MjA3NDYyOTEzM30.tJgVURdWFdOMh1wDGSIDA5h1noFVdLcOUooRiRKhay4"
SUPABASE_BUCKET = "menu-images"

[app]
APP_TITLE = "Caffe Order"
BRAND = "Caffe Dehh"